image: node:10.15.3

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - echo "only on master"
            - npm install
            - npm run build
            - pipe: atlassian/rsync-deploy:0.3.2
              variables:
                USER: $SERVER_USER
                SERVER: $SERVER_HOST
                REMOTE_PATH: $PROJECT_PATH
                LOCAL_PATH: "./dist"
